branch-defaults:
  master:
    environment: RabbitMqCluster-Beanstalk-dev
    group_suffix: null
global:
  application_name: RabbitMqCluster-Beanstalk
  branch: null
  default_ec2_keyname: eb-cli
  default_platform: Docker 17.03.1-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
